CREATE TABLE IF NOT EXISTS `incidents` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` int(11) NOT NULL,
  `incident_date` date NOT NULL,
  `incident_time` time NOT NULL,
  `location` varchar(255) NOT NULL,
  `barangay` varchar(100) NOT NULL,
  `animal_type` varchar(50) NOT NULL,
  `animal_color` varchar(100) DEFAULT NULL,
  `animal_size` varchar(50) DEFAULT NULL,
  `animal_distinguishing_features` text DEFAULT NULL,
  `victim_name` varchar(100) NOT NULL,
  `victim_age` int(3) DEFAULT NULL,
  `victim_contact` varchar(50) DEFAULT NULL,
  `injury_description` text NOT NULL,
  `severity_level` enum('Low','Medium','High','Critical') DEFAULT 'Medium',
  `status` enum('New','Under Review','Resolved','Closed') DEFAULT 'New',
  `treatment_received` text DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  KEY `incident_date` (`incident_date`),
  KEY `severity_level` (`severity_level`),
  CONSTRAINT `fk_incidents_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
